url: 'http://localhost:3003'
port: 3003
debug: false

mongodb:
  server:   localhost
  database: uptime
  user:     root
  password:
  connectionString: mongodb://localhost/uptime      # alternative to setting server, database, user and password separately

monitor:
  name:                   origin
  apiUrl:                 'http://localhost:3003/api' # must be accessible without a proxy
  pollingInterval:        10000      # ten seconds
  timeout:                5000       # five seconds
  userAgent:              NodeUptime/3.0 (https://github.com/fzaninotto/uptime)
  debug:                  false

analyzer:
  updateInterval:         60000      # one minute
  qosAggregationInterval: 600000     # ten minutes
  pingHistory:            8035200000 # three months

autoStartMonitor: true

plugins:
  - ./plugins/console
  - ./plugins/patternMatcher
  - ./plugins/httpOptions
  - ./plugins/httpsOAuthOptions
  #- ./plugins/hipchat
  #- ./plugins/victorops
  #- ./plugins/statushub
  #- ./plugins/statuspage

#hipchat:
#  apiKey: "REPLACE_WITH_HIPCHAT_APIKEY" # HipChat Admin API Key https://www.hipchat.com/admin/api
#  tag:
#    hipchat: REPLACE_WITH_HIPCHAT_ROOM  # tag name : HipChat room ID where send notification

#victorops:
#  endpoint: "REPLACE_WITH_VICTOROPS_ENDPOINT"

#statushub:
#  endpoint: https://statushub.io/api/status_pages #the same for all
#  subdomains: REPLACE_WITH_STATUSHUB_SUBDOMAINS # for example ["my_stuff"] as you can have a number of different status pages
#  apiKey: REPLACE_WITH_STATUSHUB_APIKEY

#statuspage:
#  endpoint: https://api.statuspage.io/v1/pages
#  pageid: REPLACE_WITH_STATUSPAGE_ID
#  apiKey: REPLACE_WITH_STATUSPAGE_APIKEY

#- ./plugins/email
# - ./plugins/basicAuth

#email:
#  method:      SMTP  # possible methods are SMTP, SES, or Sendmail
#  transport:         # see https://github.com/andris9/nodemailer for transport options
#    service:   Gmail # see https://github.com/andris9/Nodemailer/blob/master/lib/wellknown.js for well-known services
#    auth:
#      user: ""         # The email account username, e.g. 'username@gmail.com'
#      pass: ""         # The email account password, e.G. 'password'
#  event:
#    up:        true
#    down:      true
#    paused:    false
#    restarted: false
#  message:
#    from:            # The message sender, e.g. 'Fred Foo <foo@blurdybloop.com>'
#    to: ""             # The message recipient, e.g. 'bar@blurdybloop.com, baz@blurdybloop.com'
  # The email plugin also uses the main `url` param for hyperlinks in the sent emails

#basicAuth:
#  username:    admin
#  password:    password
#verbose: true # only used in dev

#webPageTest:
#  server: 'http://www.webpagetest.org'
#  key:
#  testOptions:
